### ISSUE TITLE
Web Server Not working.

### ISSUE THREAD

**Issue by DheeranYuvaraj** [socketbind/esp32-led-effects-server#1]
Hi,

I followed the readme file. If i connect to ip(got ip) it is not connecting to server

**Comment by socketbind** [comment]
Hi @DheeranYuvaraj,

I do not have my devkit handy at the moment so I can't be much of a help right now. No idea on why you can't connect. If it says that it got an IP in the UART console then it should be definitely available on port 80. It used to work very reliably for me so I suggest you to double check whether everything is correct with your wifi and firewall settings on your network.

The source is provided mostly for others to hack on and I do not intend to maintain it anymore or support it. Feel free to fork it and make some improvements! I would be especially happy if someone would make this work with the latest IDF SDK.

**Comment by DheeranYuvaraj** [comment]
Hi @socketbind 

It is working with IP. Can you tell me how to use mDNS instead of IP address. For example [http://gebdisplay.local/](url)
